lastfm:
  applicationName: "lastfm-scrobbler"
  apiKey: ""
  sharedSecret: ""
  registeredTo: ""
  userLoginToken: ""
  userUsername: ""
  userPassword: ""

log:
  path: ./.logs
  level: info

musixmatch:
  apiKey: ""

database:
  path: ".storage/tracks.db"

http:
  port: "8081"

telemetry:
  name: "lastfm-scrobbler"

scrobblers:
  - "Apple Music"