lastfm:
  applicationName: "lastfm-scrobbler"
  apiKey: ""
  sharedSecret: ""
  registeredTo: ""
  userLoginToken: ""
  userUsername: ""
  userPassword: ""

log:
  path: ./.logs
  level: info

musixmatch:
  apiKey: ""

database:
  type: "sqlite"  # "sqlite" or "mysql"
  path: ".storage/tracks.db"
  mysql:
    host: "localhost"
    port: 3306
    user: "user"
    password: "password"
    database: "lastfm_scrobbler"

http:
  port: "8081"

telemetry:
  name: "lastfm-scrobbler"

redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  db: 0

scrobblers:
  - "Apple Music"

isDev: true